name: Tauri Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    name: Build for Linux (AppImage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            squashfs-tools

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: linux-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: linux-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: linux-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: linux-cargo-build-

      - name: Build Tauri app for Linux
        run: cargo tauri build

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: target/release/bundle/appimage/*.AppImage
          if-no-files-found: warn

  build-windows:
    name: Build for Windows (NSIS installer)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.USERPROFILE }}\.cargo\registry
            ${{ env.USERPROFILE }}\.cargo\git
          key: windows-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: windows-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: windows-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: windows-cargo-build-

      - name: Build Tauri app for Windows
        run: cargo tauri build

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: target/release/bundle/nsis/*.exe
          if-no-files-found: warn

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Display structure
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/linux-artifacts/**/*.{AppImage,deb}
            artifacts/windows-artifacts/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
